# Generated by Django 2.1.7 on 2019-03-25 14:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_auto_20190324_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilesOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.FileField(help_text='Introduce only format images .png , .tif ,.tiff , .bmp , .webm , .ogg , .mp4 ', upload_to='images/imagenes/imagenes-output/', validators=[django.core.validators.FileExtensionValidator(['BMP', 'PNG', 'TIF', 'TIFF', 'MP4', 'OGG', 'WEBM', 'MP4'], 'The image was not uploaded:invalid format')], verbose_name='file')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
            },
        ),
        migrations.CreateModel(
            name='FilesOutput2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen2', models.FileField(help_text='Introduce only format images .png , .tif , .avi , .wmv , .mp4 , .tiff or .bmp ', upload_to='images/imagenes2/imagenes-output', validators=[django.core.validators.FileExtensionValidator(['BMP', 'PNG', 'TIF', 'TIFF', 'MP4', 'AVI', 'MOV', 'WMV'], 'The image was not uploaded:invalid format')], verbose_name='file2')),
                ('timestamp2', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'File2',
                'verbose_name_plural': 'Files2',
            },
        ),
        migrations.CreateModel(
            name='FilesOutput3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen3', models.FileField(help_text='Introduce only format images .png , .tif , .avi , .wmv , .mp4 , .tiff or .bmp ', upload_to='images/imagenes3/imagenes-output/', validators=[django.core.validators.FileExtensionValidator(['BMP', 'PNG', 'TIF', 'TIFF', 'MP4', 'AVI', 'MOV', 'WMV'], 'The image was not uploaded:invalid format')], verbose_name='file3')),
                ('timestamp3', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'File3',
                'verbose_name_plural': 'Files3',
            },
        ),
    ]
