# Generated by Django 2.1.7 on 2019-03-25 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_filesoutput_filesoutput2_filesoutput3'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filesoutput',
            options={'verbose_name': 'FileOutput', 'verbose_name_plural': 'FilesOutput'},
        ),
        migrations.AlterModelOptions(
            name='filesoutput2',
            options={'verbose_name': 'FileOutput2', 'verbose_name_plural': 'FilesOutput2'},
        ),
        migrations.AlterModelOptions(
            name='filesoutput3',
            options={'verbose_name': 'FileOutput3', 'verbose_name_plural': 'FilesOutput3'},
        ),
    ]
