# Generated by Django 2.1.7 on 2019-03-27 12:54

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0008_auto_20190326_1923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filesoutput',
            old_name='imagen',
            new_name='imagenOutput',
        ),
        migrations.RemoveField(
            model_name='filesoutput2',
            name='imagen2',
        ),
        migrations.RemoveField(
            model_name='filesoutput3',
            name='imagen3',
        ),
        migrations.AddField(
            model_name='filesoutput2',
            name='imagenOutput2',
            field=models.FileField(default=django.utils.timezone.now, help_text='Introduce only format images .png , .tif , .avi , .wmv , .mp4 , .tiff or .bmp ', upload_to='images/imagenes2/imagenes-output', validators=[django.core.validators.FileExtensionValidator(['BMP', 'PNG', 'TIF', 'TIFF', 'MP4', 'AVI', 'MOV', 'WMV'], 'The image was not uploaded:invalid format')], verbose_name='fileOutput2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filesoutput3',
            name='imagenOutput3',
            field=models.FileField(default=django.utils.timezone.now, help_text='Introduce only format images .png , .tif , .avi , .wmv , .mp4 , .tiff or .bmp ', upload_to='images/imagenes3/imagenes-output/', validators=[django.core.validators.FileExtensionValidator(['BMP', 'PNG', 'TIF', 'TIFF', 'MP4', 'AVI', 'MOV', 'WMV'], 'The image was not uploaded:invalid format')], verbose_name='fileOutput3'),
            preserve_default=False,
        ),
    ]
