# Generated by Django 2.1.7 on 2019-03-28 10:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0009_auto_20190327_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='imagen',
            field=models.FileField(help_text='Introduce only format images .png , .tif ,.tiff , .bmp , .webm , .ogg , .mp4 ', upload_to='images/imagenes/', validators=[django.core.validators.FileExtensionValidator(['BMP', 'PNG', 'PAR', 'TIFF', 'MP4', 'OGG', 'WEBM', 'MP4'], 'The image was not uploaded:invalid format')], verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='files2',
            name='imagen2',
            field=models.FileField(help_text='Introduce only format images .png , .tif , .avi , .wmv , .mp4 , .tiff or .bmp ', upload_to='images/imagenes2/', validators=[django.core.validators.FileExtensionValidator(['BMP', 'PNG', 'PAR', 'TIFF', 'MP4', 'AVI', 'MOV', 'WMV'], 'The image was not uploaded:invalid format')], verbose_name='file2'),
        ),
        migrations.AlterField(
            model_name='files3',
            name='imagen3',
            field=models.FileField(help_text='Introduce only format images .png , .tif , .avi , .wmv , .mp4 , .tiff or .bmp ', upload_to='images/imagenes3/', validators=[django.core.validators.FileExtensionValidator(['BMP', 'PNG', 'PAR', 'TIFF', 'MP4', 'AVI', 'MOV', 'WMV'], 'The image was not uploaded:invalid format')], verbose_name='file3'),
        ),
    ]
