# Generated by Django 2.1.7 on 2019-03-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0010_auto_20190328_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesoutput',
            name='in_file_1',
            field=models.IntegerField(default=0, verbose_name='first_file'),
        ),
        migrations.AddField(
            model_name='filesoutput',
            name='in_file_2',
            field=models.IntegerField(default=0, verbose_name='secondg_file'),
        ),
        migrations.AlterField(
            model_name='filesoutput',
            name='imagenOutput',
            field=models.FileField(upload_to='images/imagenes/imagenes-output/', verbose_name='fileOutput'),
        ),
    ]
