# Generated by Django 2.1.7 on 2019-03-29 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0011_auto_20190328_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesoutput',
            name='path_file_1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='filesoutput',
            name='path_file_2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='filesoutput',
            name='in_file_2',
            field=models.IntegerField(default=0, verbose_name='second_file'),
        ),
    ]
