# Generated by Django 2.1.7 on 2019-03-29 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0012_auto_20190328_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesoutput2',
            name='in_file_1',
            field=models.IntegerField(default=0, verbose_name='first_file'),
        ),
        migrations.AddField(
            model_name='filesoutput2',
            name='in_file_2',
            field=models.IntegerField(default=0, verbose_name='second_file'),
        ),
        migrations.AddField(
            model_name='filesoutput2',
            name='path_file_1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='filesoutput2',
            name='path_file_2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='filesoutput3',
            name='in_file_1',
            field=models.IntegerField(default=0, verbose_name='first_file'),
        ),
        migrations.AddField(
            model_name='filesoutput3',
            name='in_file_2',
            field=models.IntegerField(default=0, verbose_name='second_file'),
        ),
        migrations.AddField(
            model_name='filesoutput3',
            name='path_file_1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='filesoutput3',
            name='path_file_2',
            field=models.CharField(default='', max_length=100),
        ),
    ]
